### PR TITLE
Set event when scheduleded job is done

### PR DESCRIPTION
**Pull request by thomascellerier**
I had botched that code when extracting the acron code from our internal tool.

### CODE REVIEW

**Comment by userappgate** [comment]
@thomascellerier why don't you use gh actions to run mypy?

**Comment by thomascellerier** [comment]
Just haven't had time to set it up yet, I want to setup mypy and *gasp*, black.

**Comment by userappgate** [comment]
Black really makes cherry picking between releases a pain in the ass, since it periodically seems to change its mind on what's the style to adopt.

**Comment by thomascellerier** [comment]
Yeah maybe not worth it to enforce it in CI until the format is more stable.

**Comment by thomascellerier** [comment]
I'll just go ahead and merge this, the fix is already deployed in production.

**Pull request merged**
